name: AdvancedTags
version: 1.2
main: me.advancedtags.AdvancedTags
api-version: "1.20"
author: "trxiuss"
license: "CC-BY-NC-4.0"
folia-supported: true
softdepend: [PlaceholderAPI]
commands:
  unvan:
    description: Tag selection menu
    aliases: ["ünvan", "tags"]
  advancedtags:
    description: Tag admin command
    aliases: ["at"]
permissions:
  advancedtags.command:
    default: true
  advancedtags.admin:
    default: op
  advancedtags.bypass.cooldown:
    default: op
  advancedtags.tag.*:
    default: op